version: '3.3'

services:

   db:
     image: %docker_image_prefix%_db
     volumes:
       - %docker_image_prefix%_db_data:/var/lib/mysql
     restart: always

     networks:
       %docker_image_prefix%_net:
         ipv4_address: ${db_addr}

     environment:
       MARIADB_DATABASE: app
       MARIADB_USER: app
       MARIADB_PASSWORD: app
       MARIADB_ROOT_PASSWORD: root
  
   app:
     image: %docker_image_prefix%_app
     ports:
      - "18080:80"
      - "18443:443"
     depends_on:
       - db

     networks:
       %docker_image_prefix%_net:
         ipv4_address: ${app_addr}

     volumes:
       - type: bind
         source: ./project
         target: /var/www/
         
     restart: always
     environment:
       DB_HOST: ${db_addr}
       DB_USERNAME: "app"
       DB_DATABASE: "app"
       DB_PASSWORD: "app"

volumes:
    %docker_image_prefix%_db_data: {}
       

networks:
  %docker_image_prefix%_net:
    ipam:
      driver: default
      config:
        - subnet: ${nw_addr}
    
